using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;
using ProgrammersBlog.Entities.Concrete;

namespace ProgrammersBlog.Data.Migrations
{
    public partial class SeedingArticles : Migration
    {
        // Sorguların Migration içerisinde saklanması için SQL Server yerine buradan eklendi.
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
            "INSERT INTO [ProgrammersBlog1DB].dbo.Articles (Title,[Content],Thumbnail,[Date],ViewsCount,CommentCount,SeoAuthor,SeoDescription,SeoTags,CategoryId,UserId,[CreatedDate],ModifiedDate,IsDeleted,IsActive,CreatedByName,ModifiedByName,Note) VALUES ('.NET5 ile Gelen Yenilikler','Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia daki Hampden-Sydney College dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan consectetur sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan de Finibus Bonorum et Malorum (iyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan Lorem ipsum dolor sit amet 1.10.32 sayılı bölümdeki bir satırdan gelmektedir. 1500 lerden beri kullanılmakta olan standard Lorem Ipsum metinleri ilgilenenler için yeniden üretilmiştir.Çiçero tarafından yazılan 1.10.32 ve 1.10.33 bölümleri de 1914 H.Rackham çevirisinden alınan İngilizce sürümleri eşliğinde özgün biçiminden yeniden üretilmiştir.','postImages/defaultThumbnail.jpg',GETDATE(),1,0,'C# Developer','C# 9.0 .NET5','C# F# .NETCORE ASP.NET MVC5',(SELECT TOP 1 Categories.Id FROM dbo.Categories),1,GETDATE(),GETDATE(),0,1,'Migration','Migration','İlk C# paylaşımı.');");
            migrationBuilder.Sql(
            "INSERT INTO[ProgrammersBlog1DB].dbo.Articles(Title, [Content], Thumbnail, [Date], ViewsCount, CommentCount, SeoAuthor, SeoDescription, SeoTags, CategoryId, UserId, [CreatedDate], ModifiedDate, IsDeleted, IsActive, CreatedByName, ModifiedByName, Note) VALUES ('C++ ile Algoritma Yapıları','Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia daki Hampden-Sydney College dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan consectetur sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan de Finibus Bonorum et Malorum (iyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan Lorem ipsum dolor sit amet 1.10.32 sayılı bölümdeki bir satırdan gelmektedir. 1500 lerden beri kullanılmakta olan standard Lorem Ipsum metinleri ilgilenenler için yeniden üretilmiştir.Çiçero tarafından yazılan 1.10.32 ve 1.10.33 bölümleri de 1914 H.Rackham çevirisinden alınan İngilizce sürümleri eşliğinde özgün biçiminden yeniden üretilmiştir.','postImages/defaultThumbnail.jpg',GETDATE(),10,0,'C++ Developer','C++ 99','C++ 99 11 20 Linked List Veri Yapıları',(SELECT TOP 1 Categories.Id FROM dbo.Categories),1,GETDATE(),GETDATE(),0,1,'Migration','Migration','İlk C++ paylaşımı.')");
            migrationBuilder.Sql(
            "INSERT INTO[ProgrammersBlog1DB].dbo.Articles(Title, [Content], Thumbnail, [Date], ViewsCount, CommentCount, SeoAuthor, SeoDescription, SeoTags, CategoryId, UserId, [CreatedDate], ModifiedDate, IsDeleted, IsActive, CreatedByName, ModifiedByName, Note) VALUES ('Asenkron Javascript','Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia daki Hampden-Sydney College dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan consectetur sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan de Finibus Bonorum et Malorum (iyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan Lorem ipsum dolor sit amet 1.10.32 sayılı bölümdeki bir satırdan gelmektedir. 1500 lerden beri kullanılmakta olan standard Lorem Ipsum metinleri ilgilenenler için yeniden üretilmiştir.Çiçero tarafından yazılan 1.10.32 ve 1.10.33 bölümleri de 1914 H.Rackham çevirisinden alınan İngilizce sürümleri eşliğinde özgün biçiminden yeniden üretilmiştir.','postImages/defaultThumbnail.jpg',GETDATE(),25,0,'Javascirpt Developer','Javascript ES6-ES7-ES8','Javascript ES6 ES7 ES8',(SELECT TOP 1 Categories.Id FROM dbo.Categories),1,GETDATE(),GETDATE(),0,1,'Migration','Migration','İlk Javascript paylaşımı.')");
            migrationBuilder.Sql(
            "INSERT INTO[ProgrammersBlog1DB].dbo.Articles(Title, [Content], Thumbnail, [Date], ViewsCount, CommentCount, SeoAuthor, SeoDescription, SeoTags, CategoryId, UserId, [CreatedDate], ModifiedDate, IsDeleted, IsActive, CreatedByName, ModifiedByName, Note) VALUES ('Python ile Veri Analizi','Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia daki Hampden-Sydney College dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan consectetur sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan de Finibus Bonorum et Malorum (iyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan Lorem ipsum dolor sit amet 1.10.32 sayılı bölümdeki bir satırdan gelmektedir. 1500 lerden beri kullanılmakta olan standard Lorem Ipsum metinleri ilgilenenler için yeniden üretilmiştir.Çiçero tarafından yazılan 1.10.32 ve 1.10.33 bölümleri de 1914 H.Rackham çevirisinden alınan İngilizce sürümleri eşliğinde özgün biçiminden yeniden üretilmiştir.','postImages/defaultThumbnail.jpg',GETDATE(),96,0,'Python Developer','Python ile Algoritmalar ve Veri Analizi','Python ile Algoritmalar ve Veri Analizi',(SELECT TOP 1 Categories.Id FROM dbo.Categories),1,GETDATE(),GETDATE(),0,1,'Migration','Migration','İlk Python paylaşımı.')");
            migrationBuilder.Sql(
            "INSERT INTO[ProgrammersBlog1DB].dbo.Articles(Title, [Content], Thumbnail, [Date], ViewsCount, CommentCount, SeoAuthor, SeoDescription, SeoTags, CategoryId, UserId, [CreatedDate], ModifiedDate, IsDeleted, IsActive, CreatedByName, ModifiedByName, Note) VALUES ('Java ile Android ve Mobil Programlama','Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia daki Hampden-Sydney College dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan consectetur sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan de Finibus Bonorum et Malorum (iyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan Lorem ipsum dolor sit amet 1.10.32 sayılı bölümdeki bir satırdan gelmektedir. 1500 lerden beri kullanılmakta olan standard Lorem Ipsum metinleri ilgilenenler için yeniden üretilmiştir.Çiçero tarafından yazılan 1.10.32 ve 1.10.33 bölümleri de 1914 H.Rackham çevirisinden alınan İngilizce sürümleri eşliğinde özgün biçiminden yeniden üretilmiştir.','postImages/defaultThumbnail.jpg',GETDATE(),235,0,'Java Developer','Java Kotlin Android','Java Kotlin Android Mobil',(SELECT TOP 1 Categories.Id FROM dbo.Categories),1,GETDATE(),GETDATE(),0,1,'Migration','Migration','İlk Java paylaşımı.')");
            migrationBuilder.Sql(
            "INSERT INTO[ProgrammersBlog1DB].dbo.Articles(Title, [Content], Thumbnail, [Date], ViewsCount, CommentCount, SeoAuthor, SeoDescription, SeoTags, CategoryId, UserId, [CreatedDate], ModifiedDate, IsDeleted, IsActive, CreatedByName, ModifiedByName, Note) VALUES ('Dart ve Flutter ile IOS & Android Programlama','Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia daki Hampden-Sydney College dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan consectetur sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan de Finibus Bonorum et Malorum (iyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan Lorem ipsum dolor sit amet 1.10.32 sayılı bölümdeki bir satırdan gelmektedir. 1500 lerden beri kullanılmakta olan standard Lorem Ipsum metinleri ilgilenenler için yeniden üretilmiştir.Çiçero tarafından yazılan 1.10.32 ve 1.10.33 bölümleri de 1914 H.Rackham çevirisinden alınan İngilizce sürümleri eşliğinde özgün biçiminden yeniden üretilmiştir.','postImages/defaultThumbnail.jpg',GETDATE(),166,0,'Flutter Developer','Flutter Dart','Flutter Dart Android IOS Mobil',(SELECT TOP 1 Categories.Id FROM dbo.Categories),1,GETDATE(),GETDATE(),0,1,'Migration','Migration','İlk Flutter paylaşımı.')");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            
        }
    }
}
